spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: (your_email_here)
    password: (your_password_here)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

cloudinary:
  cloud_name: your_cloud_name
  api_key: your_api_key
  api_secret: your_secret