spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: (your_email_here)
    password: (your_password_here)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true