spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_flow
    username: root
    password: bach2612
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:

  config:
    import: optional:file:secret.yml

jwt:
  refreshTokenExpirationMs: 2592000000

